project:
  type: book
  pre-render: make quarto-prerender
  output-dir: docs

book:
  title: "Introduction to Stata"
  sidebar:
    title: "Introduction to Stata"
  chapters:
    - index.qmd
    - 01-the-basics-of-stata.qmd
    - 02-working-with-data-sets.qmd
    - 03-data-management.qmd
    - 04-data-manipulation.qmd
    - 05-programming.qmd
    - appendix.qmd

format:
  html:
    theme: cosmo
    callout-appearance: simple
