project:
  type: book
  pre-render: make quarto-prerender
  output-dir: docs

book:
  title: "Introduction to Stata"
  chapters:
    - index.qmd
    - 02-the-basics-of-stata.qmd
    - 03-working-with-data-sets.qmd
    - 04-data-management.qmd
    - 05-data-manipulation.qmd
    - 06-programming.qmd
    - 07-appendix.qmd

format:
  html:
    theme: cosmo
    callout-appearance: simple
