---
title: "Introduction to Stata"
author: "CSCAR Staff"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    config:
      sharing: null
documentclass: book
link-citations: yes
github-repo: rstudio/bookdown-demo
---

# Preface

These notes are split into four primary sections:

- [Chapter 2: The Basics of Stata](the-basics-of-stata.html) - Interacting with Stata.
- [Chapter 3: Working with Data Sets](working-with-data-sets.html) - Importing, opening, and saving data sets.
- [Chapter 4: Data Management](data-management.html) - The basics of maintaining and exploring a data set.
- [Chapter 5: Data Manipulation](data-manipulation.html) - Creating and modifying variables and other ways of manipulating your data.

These sections will generally be presented in sequence. The discussion will alternate between theory and practice. The format will alternate between
lecture and exercises. Please ask questions as soon as they arise in your mind. Please provide feedback or voice concerns.

There are two additional sections:

- [Chapter 6: Programming & Advanced Topics](programming-advanced-features.html) - Topics for users who wish to move beyond the basics.
- [Appendix](appendix.html) - Houses the exercise solutions.

## How to use this document

These notes are published in [bookdown](https://bookdown.org/) format which enables easy creation of longform documents (using a mixture of
[markdown](https://daringfireball.net/projects/markdown/), [R](https://www.r-project.org/), and for these notes specifically,
[Stata](http://www.stata.com/)'s [dyndoc](http://www.stata.com/manuals/pdyndoc.pdf), which was added in Stata 15).

The table of contents is found on the left hand side, with subsections expanding below the current section. At the top of the page are four icons,
from left to right they 1) Hide/show the table of contents, 2) Search this document, 3) Change the font the book is displayed in, and 4) Display
keyboard shortcuts.

All images should link to full-size versions to see detail if needed.

## Contact information

### CSCAR

- Current contact for questions about the notes: Josh Errickson (jerrick@umich.edu)
- Office Hours: Monday-Friday 9am to 5pm (Closed Tuesday 12-1pm)
- Phone: 734.764.7828
- Statistical Assistance: stats-consulting@umich.edu
- Data Science Assistance: ds-consulting@umich.edu
- High Performance Computing: hpc-consulting@umich.edu
- http://cscar.research.umich.edu/


## Acknowledgments

These notes have evolved over the years thanks to many CSCAR statisticians, including Josh Errickson, Giselle Kolenic, Brady West, Heidi Reichert, and
Lingling Zhang.

This material was created for use in workshops and short courses presented by faculty and staff from the Consulting for Statistics, Computing \&
Analytics Research (CSCAR) at the University of Michigan. No part of this material may be used for other purposes, copied, changed, or sold.
